<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib\Tests\Controllers;

use SwaggerPetstoreLib\Controllers\StoreController;
use SwaggerPetstoreLib\Exceptions;

class StoreControllerTest extends BaseTestController
{
    /**
     * @var StoreController StoreController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getStoreController();
    }

    public function testGetInventory()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->getInventory();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
