<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing HttpBasic security credentials.
 */
class HttpBasicCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for HttpBasicCredentialsBuilder
     *
     * @param string $username
     * @param string $passwprd
     */
    public static function init(string $username, string $passwprd): self
    {
        return new self(['username' => $username, 'passwprd' => $passwprd]);
    }

    /**
     * Setter for Username.
     *
     * @param string $username
     *
     * @return $this
     */
    public function username(string $username): self
    {
        $this->config['username'] = $username;
        return $this;
    }

    /**
     * Setter for Passwprd.
     *
     * @param string $passwprd
     *
     * @return $this
     */
    public function passwprd(string $passwprd): self
    {
        $this->config['passwprd'] = $passwprd;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
