<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib\Authentication;

use Core\Authentication\CoreAuth;
use Core\Request\Parameters\HeaderParam;
use Core\Utils\CoreHelper;

/**
 * Utility class for authorization and token management.
 */
class HttpBasicManager extends CoreAuth implements HttpBasicCredentials
{
    private $username;

    private $passwprd;

    /**
     * Returns an instance of this class.
     *
     * @param string $username
     * @param string $passwprd
     */
    public function __construct(string $username, string $passwprd)
    {
        parent::__construct(
            HeaderParam::init('Authorization', CoreHelper::getBasicAuthEncodedString($username, $passwprd))
                ->requiredNonEmpty()
        );
        $this->username = $username;
        $this->passwprd = $passwprd;
    }

    /**
     * String value for username.
     */
    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * String value for passwprd.
     */
    public function getPasswprd(): string
    {
        return $this->passwprd;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $username
     * @param string $passwprd
     */
    public function equals(string $username, string $passwprd): bool
    {
        return $username == $this->username &&
            $passwprd == $this->passwprd;
    }
}
