<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreLib\Models\Category2;

/**
 * Builder for model Category2
 *
 * @see Category2
 */
class Category2Builder
{
    /**
     * @var Category2
     */
    private $instance;

    private function __construct(Category2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new category 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new Category2());
    }

    /**
     * Sets id field.
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new category 2 object.
     */
    public function build(): Category2
    {
        return CoreHelper::clone($this->instance);
    }
}
