<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreLib\Models\Category2;
use SwaggerPetstoreLib\Models\PetRequest;

/**
 * Builder for model PetRequest
 *
 * @see PetRequest
 */
class PetRequestBuilder
{
    /**
     * @var PetRequest
     */
    private $instance;

    private function __construct(PetRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new pet request Builder object.
     */
    public static function init(string $name, array $photoUrls): self
    {
        return new self(new PetRequest($name, $photoUrls));
    }

    /**
     * Sets id field.
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets category field.
     */
    public function category(?Category2 $value): self
    {
        $this->instance->setCategory($value);
        return $this;
    }

    /**
     * Sets tags field.
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new pet request object.
     */
    public function build(): PetRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
