<?php

declare(strict_types=1);

/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models\Builders;

use Core\Utils\CoreHelper;
use SwaggerPetstoreLib\Models\StoreOrderRequest;

/**
 * Builder for model StoreOrderRequest
 *
 * @see StoreOrderRequest
 */
class StoreOrderRequestBuilder
{
    /**
     * @var StoreOrderRequest
     */
    private $instance;

    private function __construct(StoreOrderRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new store order request Builder object.
     */
    public static function init(): self
    {
        return new self(new StoreOrderRequest());
    }

    /**
     * Sets id field.
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets pet id field.
     */
    public function petId(?int $value): self
    {
        $this->instance->setPetId($value);
        return $this;
    }

    /**
     * Sets quantity field.
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Sets ship date field.
     */
    public function shipDate(?\DateTime $value): self
    {
        $this->instance->setShipDate($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets complete field.
     */
    public function complete(?bool $value): self
    {
        $this->instance->setComplete($value);
        return $this;
    }

    /**
     * Initializes a new store order request object.
     */
    public function build(): StoreOrderRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
